### ISSUE TITLE
Add a python linter to check for code integrity

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/openroberta-lab#304] opened 2019-11-12 10:28 UTC
As commented in #110:
- The microbit compiler always passes -> microbit integration tests are useless
- Python programs in general will only fail on the robot -> no integration tests for python robots possible
- microbit compiler output is invalid if `uflash` is missing -> integration tests will pass, a file is generated

This should be improved by adding a python linting library:
- [ ] Research a fitting library
- [ ] Integrate into workflows, either as standalone worker or in the compile worker
- [ ] Adapt integration tests to include and validate the linting
- [ ] (Show linting output to users, similar to compiler errors)
- [ ] (Check for output of microbit compiler, to validate `uflash` is installed)

**Comment by rbudde** [comment] 2023-11-14 12:29
Duplicate of #1313

**Closed** 2023-11-14 12:30 UTC
Labels: duplicate, enhancement
