### ISSUE TITLE
EV3: Set Motor For Rotation/Degrees Not Working Properly

### ISSUE THREAD

**Issue by RohanCheri** [OpenRoberta/openroberta-lab#475] opened 2020-01-02 23:06 UTC
**Describe the bug**
 When using the set motor port to power for a certain amount of rotations/degrees, the robot moves an insignificant amount.

**To Reproduce**
1. Go to Advanced Tools -> Actions -> Move
2. Drag on "Motor Port B on speed % 30 / for rotation 1" block into the program
3. Run the program

**Expected behavior**
The robot moves a considerable amount based on the inputted values, for both degrees and rotations.

**Screenshots**
Example of the robot moving with 1 rotation. (You have to look really closely to see a small movement)
![1RotationNotWorking](https://user-images.githubusercontent.com/34838212/71698718-7af78500-2d8a-11ea-9de6-c922e4d93675.gif)

**Device information**
 - Type Desktop
 - OS: Windows 10
 - Browser: Chrome 79.0.3945.88
--

**Additional context**
One rotation should not be an inconsequentially small movement. With the current block, an input of 1800 rotations causes the robot to make a nearly 90-degree turn.

**Comment by boonto** [comment] 2020-01-03 07:45
Duplicate of #390, it is already fixed on develop.

**Closed by boonto** 2020-01-03 07:45 UTC
