### ISSUE TITLE
Integrate a Python linter for QC

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#1313] opened 2022-05-24 09:05 UTC
our integration tests generate programs in the target labguage. If these programs can be compiled (C++, Java), this is done to detect errors of the code generator.

For Python this is not possible this way. It would be helpful to take a Python linter and check the results.

This refers to **tests**. It is a good first issue after contacting the development team.

**Comment by RaghuvirShirodkar** [comment] 2022-10-13 11:32
Duplicate of #304

**Closed** 2024-06-27 14:31 UTC
Labels: enhancement, good first issue
