### ISSUE TITLE
EV3: 'Reset Bricklight' Block Does Not Do What Its Description Says

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#665] opened 2020-01-22 07:26 UTC
**Describe the bug**
 - The 'reset bricklight' block has a description saying that it resets bricklight and sets the default bricklight: green and blinking. When the block is used, it does not do that.

**To Reproduce**
1. Switch to EV3.
2. Spawn the 'reset bricklight' block.
3. See that it does not do what its description says.

**Expected behavior**
 - It should do what its description says. 

(or)

- The description should be changed.

**GIF**
 - 
![Screen Recording 2020-01-22 at 12 55 48 74 PM](https://user-images.githubusercontent.com/44456350/72873734-8d743700-3d16-11ea-8d55-15174cfe5eb5.gif)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by boonto** [comment] 2020-01-22 09:03
Duplicate of #481.

**Closed by boonto** 2020-01-22 09:03 UTC
Labels: duplicate
