### ISSUE TITLE
Condition `true == null` causes incorrect behaviour in simulation

### ISSUE THREAD

**Issue by Caffetaria** [OpenRoberta/openroberta-lab#493] opened 2020-01-04 16:05 UTC
**Describe the bug**
 - When an 'if' block is used with the condition true != null, the do block does not execute.
This is not the expected behaviour in usual programming languages.

**To Reproduce**
1. Create a nepo program.
2. Use the if block.
3. Use the condition "true != null".
4. Do statement does not execute in the simulation.

**Expected behavior**
 - The 'do' statement of the 'if' block should execute as "true != null" evaluates to true.

**Screenshots**
- 
<img width="1041" alt="Screen Shot 2020-01-04 at 9 30 49 PM" src="https://user-images.githubusercontent.com/9400738/71768138-8dfc8780-2f39-11ea-8c45-c49aa030d808.png">

<img width="1189" alt="Screen Shot 2020-01-04 at 9 25 43 PM" src="https://user-images.githubusercontent.com/9400738/71768054-d10a2b00-2f38-11ea-8984-067e920bbce5.png">

**Device information**
 - Type: Desktop
 - OS: MacOS
 - Browser: Chrome

**Additional context**
 - Seems to happen in other robot simulations as well.

**Comment by bjost2s** [comment] 2020-02-12 09:14
should be fixed together with #306

**Comment by RaghuvirShirodkar** [comment] 2022-10-04 07:49
Seems to be solved with the new simulation.

![test](https://user-images.githubusercontent.com/43172112/193764092-498c1c47-a145-4576-b27d-5e65d9cb6073.gif)

**Comment by bjost2s** [comment] 2022-10-04 09:23
The problem is not solved, because "if true == null" produces same result.

**Closed** 2022-10-24 13:24 UTC
Labels: bug, resolved, simulation
