### ISSUE TITLE
Calliope: test if true if false block produces server error

### ISSUE THREAD

**Issue by Blippy2019** [OpenRoberta/openroberta-lab#500] opened 2020-01-05 04:12 UTC
**Describe the bug**
 - Block causes server error when used

**To Reproduce**
1. Connect test if true if false block to show text
2. Enter any values as inputs
3. Run simulation

**Expected behavior**
 - The test block returns a value
 - Expected behavior of image below: Calliope displays the number 2

**Screenshots**
![image](https://user-images.githubusercontent.com/58810680/71775019-a3bb8c80-2fcd-11ea-81f8-ad3e85658753.png)

**Device information**
 - Desktop
 - Windows 10
 - Chrome

**Comment by boonto** [comment] 2020-01-05 09:40
Duplicate of #322.

**Closed by boonto** 2020-01-05 09:40 UTC
