### ISSUE TITLE
x/y coordinates LED reading/writing seems inverted

### ISSUE THREAD

**Issue by thoschi** [OpenRoberta/openroberta-lab#1585] opened 2023-12-01 12:37 UTC
**Describe the bug**
 - On Calliope x/y coordinates when reading LEDs seems mixed up

**To Reproduce**
1. set LED (0,1) to brightness 5
2. read LED (0,1) -> brightness 0
3. read LED (1,0) -> brightness 5

**Expected behavior**
 - x/y coordinates of LED reading should be the same as in LED writing

**Device information**
 - OS: Ubuntu 23.10
 - Browser Firefox 120.0

**Comment by AyaMoussa** [comment] 2024-02-13 13:08
Solved (duplicate of issue 1609)

**Closed by AyaMoussa** 2024-02-13 13:08 UTC
Labels: bug
