### ISSUE TITLE
MBot2 zeigt 'NO_PORT' im Programmierblock

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#1579] opened 2023-11-14 15:12 UTC
- select MBot2
- see in the configuration, that there are two encode motors named R and L
- switch to the programming tab and select the drive block from the advanced tool box

- the block shows NO_PORT

The Block has to show a dropdown with the values R and L, R pre-seelcted

**Comment by rbudde** [comment] 2023-11-15 09:25
see the attached image: one of the two blocks is affected only
![2023-11-15 10_24_41-Open Roberta Lab](https://github.com/OpenRoberta/openroberta-lab/assets/15834363/76bbf7b4-34fc-4ea2-842d-d5d60556077a)

**Comment by heini208** [comment] 2023-11-15 10:11
Caused By the added && !'joycar' [here](https://github.com/OpenRoberta/blockly/blob/e976d624050459a84525681a3ca379086a303f0b/blocks/robActions.js#L208C50-L208C50) 

!this.workspace.device === 'joycar' is always false which causes encoders to not work here anymore.

**Comment by heini208** [comment] 2023-11-15 15:05
Resolved in [this](https://github.com/OpenRoberta/openroberta-lab/commit/5dbb123ef2ce2ade218f4f6e74fa2f7c734526dd) Commit adding [this](https://github.com/OpenRoberta/blockly/commit/53281c54c17927d8c6c9745f63ff6510bb028eda) Blockly Commit.

**Closed** 2023-11-17 16:41 UTC
Labels: bug, frontend, hotfix, blockly
