### ISSUE TITLE
List Blocks Do Not Automatically Remove Deleted List Positions

### ISSUE THREAD

**Issue by nishanth1232** [OpenRoberta/openroberta-lab#677] opened 2020-01-22 15:54 UTC
**Describe the bug**
 - When a list block is spawned and the list items are removed, the items attached do not get deleted. 

**To Reproduce**
1. Go to the lab.
2. Spawn a 'create list' block.
3. Delete list entries.
4. See that the entries actually do not get deleted.

**Expected behavior**
 - Automatic removal of deleted list items.

**GIF**
 - 
![Screen Recording 2020-01-22 at 09 24 20 63 PM](https://user-images.githubusercontent.com/44456350/72909803-99371c00-3d5d-11ea-8708-fe64a7da4ae3.gif)

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by boonto** [comment] 2020-01-23 08:38
Duplicate of #440, please check previous issues :)

**Closed by boonto** 2020-01-23 08:38 UTC
Labels: duplicate
