### ISSUE TITLE
Multiple Robot Simulation: Over 9 robots produces error

### ISSUE THREAD

**Issue by KevinL10** [OpenRoberta/openroberta-lab#555] opened 2020-01-17 15:43 UTC
**Describe the bug**
 - When the user chooses over 10 robots to be part of a multiple robot simulation, only one robot will be shown, which is desired. However, the sensor data dropdown menu will still have 9 colours to choose from.

**To Reproduce**
1. Create a multiple robot simulation with over 10 robots
2. Go to sensor data
3. Open the dropdown

**Expected behavior**
 - Either alert the user that there cannot be more than 9 robots in a multi simulation, or make the dropdown show only one colour.

**Screenshots**
 -
![Screenshot (97)](https://user-images.githubusercontent.com/58920989/72625103-003b7780-38fd-11ea-9344-1ec7f0958d27.png)

**Device information**
 - Type: Desktop
 - OS: Windows 10
 - Browser: Chrome

**Comment by boonto** [comment] 2020-01-17 19:15
May be a duplicate of #557.

**Comment by boonto** [comment] 2020-03-06 10:51
In order to solve this we should limit the selectable amount of robots to 9.

**Comment by sachinsshetty** [comment] 2020-04-02 04:31
Issue not reproducible in version 3.8.5.
After selecting 12 program in multiple robot simulation, the dropdown in sensor view shows all 12 color for robots.
Tested on Ubuntu 18.04, firefox 74.0.

**Comment by bjost2s** [comment] 2023-06-05 07:50
fixed with #907

**Closed by bjost2s** 2023-06-05 07:50 UTC
Labels: bug, simulation
