### ISSUE TITLE
Microbit: Empty value in show block breaks program execution

### ISSUE THREAD

**Issue by Blippy2019** [OpenRoberta/openroberta-lab#509] opened 2020-01-07 09:11 UTC
**Describe the bug**
 - The program gets 'stuck' when an empty text block is used with a show text or character block. Any code after these blocks will not execute.

**To Reproduce**
1. Go to show text block
2. Delete the text in the string block
3. Add any code after
4. Run simulation and see error

**Expected behavior**
 - A warning, e.g. 'this block will not execute' or 'missing input'
 - Program should continue after this block, any program after this block should execute

**Screenshots**
 - In the program below, the image is never displayed
![image](https://user-images.githubusercontent.com/58810680/71882975-8c290300-3189-11ea-9ce0-6c321572d9c6.png)

**Device information**
 - Desktop
 - Windows 10
 - Chrome

**Comment by boonto** [comment] 2020-01-07 13:18
As far as I can tell this seems like a duplicate of #455.

**Closed by boonto** 2020-01-07 13:18 UTC
Labels: bug, simulation
