### ISSUE TITLE
ä will not be shown

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1368] opened 2022-09-23 14:51 UTC
**Describe the bug**
 - The letter "ä" will not be shown at the calliope (but the simulation is fine)

**To Reproduce**
1. Go to 'Calliope mini'
2. Click on block "show text"
3. Type a word with "ä"

**Expected behavior**
 - Ä as small ä will be shown

**Screenshots**
 - If applicable, add screenshots to help explain your problem.

**Device information**
 - Type Desktop
 - OS: windows
 - Browser chrome

**Additional context**
 - Add any other context about the problem here.

**Comment by RaghuvirShirodkar** [comment] 2022-10-12 20:35
Duplicate of #371 (?)

**Comment by bjost2s** [comment] 2022-10-13 05:45
This is a firmware problem/feature, you should create a ticket directly at Calliope / mbed

**Comment by Thorlogy** [comment] 2022-10-13 06:59
Would it be possible to show a note/hint that ä (umlaute) can not be shown on the Calliope mini? 
It should also be descriped in the help text:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/19221359/195524442-0f808ecb-0511-4849-aa4e-f2f950b06bd7.png">

**Closed** 2022-10-13 12:01 UTC
